### ISSUE TITLE
Customizations are not restored, custom.el remains empty

### ISSUE THREAD

**Issue by zigmhount** [corvideon/mousemacs#1]
Hi!
First of all, thanks for your neat project :) I've been using emacs for a few months so I'm still only a beginner, and I like very much your mouse-and-menus approach, which will help me very much to gradually learn emacs shortcuts when they are displayed in the menus.
However, over the past months I had gathered some customization into my ~/.emacs file, and I am somewhat struggling to move that into the mousemacs configuration structure - especially since I do not know precisely in which order what should be called (I should probably attentively read some documentation on this at some point)...
After several attempts, I ended up adding many things in init.el before `(package-initialize)` (mostly melpa stuff and org-mode customization), since adding stuff in custom.el does not seem to have any effect.
However, all the things that I may configure through emacs' Customize menu seem to be forgotten whenever I restart emacs, and custom.el remains desperately empty despite the message `Wrote /home/../.emacs.d/custom.el` being displayed when I save a customization for future session with the GUI menu.
Previously opened files are also not reopened even when I activate `desktop-save-mode`.
Is this the expected behaviour, how should I proceed to save my customization?

This might very well be a silly question, or a real issue with the current mousemacs configuration, so apologies if it isn't!

Thanks!

**Comment by seamus-brady** [comment]
Sorry zigmhount  - I missed this issue when you opened it :)
I hope that the issue has passed but to be honest I could not support a "mix and match" approach to mousemacs as there are too many variables. I would suggest starting with a clean mousemacs and then gradually adapting it back to what you like, rather than adding mousemacs to an existing config.
