### ISSUE TITLE
Chaging themes or settings simply don't "stick" after restart.

### ISSUE THREAD

**Issue by phunni** [corvideon/mousemacs#4]
I've tried to change the theme of my emacs after installing mousemacs, but, when I restart, it reverts to the default theme. I'm changing the theme via the menus Options > Customize Emacs > Custom Themes.

I can succesfully change themes in there, but it never lasts beyond a restart.

Also, any action I do seems to create/duplicate tabs/windows/buffers - I'm not certain what they are. These are then difficult to get rid of. 

I installed mousemacs as suggested by backing up .emacs.d, then deleting it and then running the git clone command in the project readme.

**Comment by seamus-brady** [comment]
I think you may need to add it to `init.el` and see if that works :)
